version: "3"

services: 
  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    volumes: 
      - d:/docker/tmp/mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment: 
      MYSQL_ROOT_PASSWORD: Root@2019