version: "3"

services: 
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root